# Form implementation generated from reading ui file 'D:\python\Hocmay\Final_HocMay\UI\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Admin(object):
    def setupUi(self, Admin):
        Admin.setObjectName("Admin")
        Admin.resize(1189, 788)
        Admin.setMaximumSize(QtCore.QSize(1189, 788))
        self.centralwidget = QtWidgets.QWidget(parent=Admin)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1191, 751))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.MainWindow = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.MainWindow.setGeometry(QtCore.QRect(10, 0, 1171, 731))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.MainWindow.setFont(font)
        self.MainWindow.setMouseTracking(False)
        self.MainWindow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.MainWindow.setAcceptDrops(False)
        self.MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.MainWindow.setStyleSheet("/* Tab đang được chọn (active) */\n"
"QTabBar::tab:selected {\n"
"    min-width: 160px;     /* Độ rộng tối thiểu của mỗi tab */\n"
"    min-height: 35px;\n"
"    background-color: #b96e7f;     /* màu hồng đậm khi chọn */\n"
"    color:#e8ddde ;                 /* chữ trắng khi chọn */\n"
"    font-weight: bold;\n"
"    border-radius: 10px;\n"
"    font: 16pt \"MS Shell Dlg 2\";\n"
"   font-weight: bold;\n"
"}\n"
"\n"
"/* Tab chưa được chọn */\n"
"QTabBar::tab:!selected {\n"
"    min-width: 160px;     /* Độ rộng tối thiểu của mỗi tab */\n"
"    min-height: 35px;\n"
"    background-color: #e8ddde;    /* hồng nhạt khi chưa chọn */\n"
"    color: #b96e7f;               /* chữ nâu đỏ */\n"
"    font-weight: normal;\n"
"    border-radius: 10px;\n"
"    font: 16pt \"MS Shell Dlg 2\";\n"
"   font-weight: bold;\n"
"}\n"
"\n"
"/* Khi rê chuột vào tab (hover) */\n"
"QTabBar::tab:hover {\n"
"    background-color: #dda0af;    /* hồng sáng hơn khi hover */\n"
"}\n"
"\n"
"/* Viền xung quanh vùng nội dung tab */\n"
"QTabWidget::pane {\n"
"    border: 2px solid #dda0af;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"")
        self.MainWindow.setIconSize(QtCore.QSize(30, 30))
        self.MainWindow.setElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.MainWindow.setObjectName("MainWindow")
        self.tabWidgetPageData = QtWidgets.QWidget()
        self.tabWidgetPageData.setObjectName("tabWidgetPageData")
        self.label_3 = QtWidgets.QLabel(parent=self.tabWidgetPageData)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(185, 110, 127);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.label_3.setObjectName("label_3")
        self.comboBoxData = QtWidgets.QComboBox(parent=self.tabWidgetPageData)
        self.comboBoxData.setGeometry(QtCore.QRect(150, 20, 371, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.comboBoxData.setFont(font)
        self.comboBoxData.setStyleSheet("background-color: rgb(232, 221, 222);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(185, 110, 127);\n"
"border: 1px solid #faf4ec; \n"
"border-radius: 10px;\n"
"   font-weight: bold;")
        self.comboBoxData.setIconSize(QtCore.QSize(30, 30))
        self.comboBoxData.setObjectName("comboBoxData")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/ic_holiday_event.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.comboBoxData.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/ic_item.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.comboBoxData.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/ic_store.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.comboBoxData.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/ic_oil.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.comboBoxData.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/ic_train.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.comboBoxData.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../images/ic_test.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.comboBoxData.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../images/ic_transaction.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.comboBoxData.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../images/ic_customer.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.comboBoxData.addItem(icon7, "")
        self.label_2 = QtWidgets.QLabel(parent=self.tabWidgetPageData)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1191, 81))
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
" \n"
"    padding: 10px;\n"
" border: 1px solid #faf4ec; \n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.tabWidgetPageData)
        self.tableWidget.setGeometry(QtCore.QRect(0, 80, 1191, 641))
        self.tableWidget.setStyleSheet("color: rgb(185, 110, 127);\n"
"background-color: rgb(250, 244, 236);\n"
"border: 1px solid #faf4ec; \n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.lineEditFilter = QtWidgets.QLineEdit(parent=self.tabWidgetPageData)
        self.lineEditFilter.setGeometry(QtCore.QRect(912, 20, 221, 41))
        self.lineEditFilter.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.lineEditFilter.setStyleSheet("background-color: rgb(232, 221, 222);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(185, 110, 127);\n"
"border: 1px solid #faf4ec; \n"
"border-radius: 10px;\n"
"   font-weight: bold;")
        self.lineEditFilter.setObjectName("lineEditFilter")
        self.label_2.raise_()
        self.label_3.raise_()
        self.comboBoxData.raise_()
        self.tableWidget.raise_()
        self.lineEditFilter.raise_()
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../images/ic_database.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.MainWindow.addTab(self.tabWidgetPageData, icon8, "")
        self.tabWidgetPageStatistic = QtWidgets.QWidget()
        self.tabWidgetPageStatistic.setObjectName("tabWidgetPageStatistic")
        self.groupBoxChart_2 = QtWidgets.QGroupBox(parent=self.tabWidgetPageStatistic)
        self.groupBoxChart_2.setGeometry(QtCore.QRect(310, 200, 881, 521))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBoxChart_2.setFont(font)
        self.groupBoxChart_2.setStyleSheet("background-color: rgb(232, 221, 222);\n"
"color: rgb(104, 83, 92);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.groupBoxChart_2.setObjectName("groupBoxChart_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.groupBoxChart_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 861, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.tabWidgetPageStatistic)
        self.groupBox.setGeometry(QtCore.QRect(0, 200, 311, 521))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
"color: rgb(104, 83, 92);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.groupBox.setObjectName("groupBox")
        self.btnPeakLowSales = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnPeakLowSales.setGeometry(QtCore.QRect(20, 30, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnPeakLowSales.setFont(font)
        self.btnPeakLowSales.setStyleSheet(" background-color: #b96e7f;     /* màu hồng đậm khi chọn */\n"
"    color:#e8ddde ;                 /* chữ trắng khi chọn */\n"
"    font-weight: bold;\n"
"    border-radius: 10px;")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../images/ic_peaklow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnPeakLowSales.setIcon(icon9)
        self.btnPeakLowSales.setIconSize(QtCore.QSize(40, 40))
        self.btnPeakLowSales.setObjectName("btnPeakLowSales")
        self.btnSalesByWeekday = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnSalesByWeekday.setGeometry(QtCore.QRect(20, 90, 261, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnSalesByWeekday.setFont(font)
        self.btnSalesByWeekday.setStyleSheet("\n"
"    background-color: #e8ddde;    /* hồng nhạt khi chưa chọn */\n"
"    color: #b96e7f;               /* chữ nâu đỏ */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"    border-radius: 10px;")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../images/ic_saleweek.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnSalesByWeekday.setIcon(icon10)
        self.btnSalesByWeekday.setIconSize(QtCore.QSize(40, 40))
        self.btnSalesByWeekday.setObjectName("btnSalesByWeekday")
        self.btnEarthquakeSales = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnEarthquakeSales.setGeometry(QtCore.QRect(10, 160, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnEarthquakeSales.setFont(font)
        self.btnEarthquakeSales.setStyleSheet(" background-color: #b96e7f;     /* màu hồng đậm khi chọn */\n"
"    color:#e8ddde ;                 /* chữ trắng khi chọn */\n"
"    font-weight: bold;\n"
"    border-radius: 10px;")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../images/ic_trend.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnEarthquakeSales.setIcon(icon11)
        self.btnEarthquakeSales.setIconSize(QtCore.QSize(30, 30))
        self.btnEarthquakeSales.setObjectName("btnEarthquakeSales")
        self.btnHolidayVsNormal = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnHolidayVsNormal.setGeometry(QtCore.QRect(10, 230, 291, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnHolidayVsNormal.setFont(font)
        self.btnHolidayVsNormal.setStyleSheet("\n"
"    background-color: #e8ddde;    /* hồng nhạt khi chưa chọn */\n"
"    color: #b96e7f;               /* chữ nâu đỏ */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"    border-radius: 10px;")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../images/ic_chartsales.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnHolidayVsNormal.setIcon(icon12)
        self.btnHolidayVsNormal.setIconSize(QtCore.QSize(30, 40))
        self.btnHolidayVsNormal.setObjectName("btnHolidayVsNormal")
        self.btnCorrelationHeatmap = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnCorrelationHeatmap.setGeometry(QtCore.QRect(20, 300, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnCorrelationHeatmap.setFont(font)
        self.btnCorrelationHeatmap.setStyleSheet(" background-color: #b96e7f;     /* màu hồng đậm khi chọn */\n"
"    color:#e8ddde ;                 /* chữ trắng khi chọn */\n"
"    font-weight: bold;\n"
"    border-radius: 10px;")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../images/ic_heatmap.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnCorrelationHeatmap.setIcon(icon13)
        self.btnCorrelationHeatmap.setIconSize(QtCore.QSize(40, 40))
        self.btnCorrelationHeatmap.setObjectName("btnCorrelationHeatmap")
        self.btnLagPlot = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnLagPlot.setGeometry(QtCore.QRect(20, 370, 271, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnLagPlot.setFont(font)
        self.btnLagPlot.setStyleSheet("\n"
"    background-color: #e8ddde;    /* hồng nhạt khi chưa chọn */\n"
"    color: #b96e7f;               /* chữ nâu đỏ */\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"    border-radius: 10px;")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../images/ic_lagplot.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnLagPlot.setIcon(icon14)
        self.btnLagPlot.setIconSize(QtCore.QSize(40, 40))
        self.btnLagPlot.setObjectName("btnLagPlot")
        self.btnYearlySales = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnYearlySales.setGeometry(QtCore.QRect(20, 440, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnYearlySales.setFont(font)
        self.btnYearlySales.setStyleSheet(" background-color: #b96e7f;     /* màu hồng đậm khi chọn */\n"
"    color:#e8ddde ;                 /* chữ trắng khi chọn */\n"
"    font-weight: bold;\n"
"    border-radius: 10px;")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../images/ic_yearsale.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnYearlySales.setIcon(icon15)
        self.btnYearlySales.setIconSize(QtCore.QSize(40, 40))
        self.btnYearlySales.setObjectName("btnYearlySales")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.tabWidgetPageStatistic)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 1191, 201))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("background-color: rgb(232, 221, 222);\n"
"color: rgb(104, 83, 92);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableWidgetListofData = QtWidgets.QTableWidget(parent=self.groupBox_2)
        self.tableWidgetListofData.setGeometry(QtCore.QRect(10, 30, 1171, 171))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidgetListofData.setFont(font)
        self.tableWidgetListofData.setStyleSheet("color: rgb(185, 110, 127);\n"
"background-color: rgb(250, 244, 236);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"\n"
"")
        self.tableWidgetListofData.setObjectName("tableWidgetListofData")
        self.tableWidgetListofData.setColumnCount(2)
        self.tableWidgetListofData.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetListofData.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetListofData.setHorizontalHeaderItem(1, item)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("../images/ic_statistic.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.MainWindow.addTab(self.tabWidgetPageStatistic, icon16, "")
        self.tabWidgetPagePredict = QtWidgets.QWidget()
        self.tabWidgetPagePredict.setObjectName("tabWidgetPagePredict")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.tabWidgetPagePredict)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 1141, 631))
        self.tabWidget.setStyleSheet("\n"
"/* Tab đang được chọn (active) */\n"
"QTabBar::tab:selected {\n"
"    min-width: 400px;     /* Độ rộng tối thiểu của mỗi tab */\n"
"    min-height: 35px;\n"
"    background-color: #b96e7f;     /* màu hồng đậm khi chọn */\n"
"    color:#e8ddde ;                 /* chữ trắng khi chọn */\n"
"    font-weight: bold;\n"
"    border-radius: 10px;\n"
"    font: 16pt \"MS Shell Dlg 2\";\n"
"   font-weight: bold;\n"
"}\n"
"\n"
"/* Tab chưa được chọn */\n"
"QTabBar::tab:!selected {\n"
"    min-width: 400px;     /* Độ rộng tối thiểu của mỗi tab */\n"
"    min-height: 35px;\n"
"    background-color: #e8ddde;    /* hồng nhạt khi chưa chọn */\n"
"    color: #b96e7f;               /* chữ nâu đỏ */\n"
"    font-weight: normal;\n"
"    border-radius: 10px;\n"
"    font: 16pt \"MS Shell Dlg 2\";\n"
"   font-weight: bold;\n"
"}\n"
"\n"
"/* Khi rê chuột vào tab (hover) */\n"
"QTabBar::tab:hover {\n"
"    background-color: #dda0af;    /* hồng sáng hơn khi hover */\n"
"}\n"
"\n"
"/* Viền xung quanh vùng nội dung tab */\n"
"QTabWidget::pane {\n"
"    border: 2px solid #dda0af;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"")
        self.tabWidget.setIconSize(QtCore.QSize(40, 40))
        self.tabWidget.setObjectName("tabWidget")
        self.tabProduct = QtWidgets.QWidget()
        self.tabProduct.setObjectName("tabProduct")
        self.label_5 = QtWidgets.QLabel(parent=self.tabProduct)
        self.label_5.setGeometry(QtCore.QRect(270, 30, 61, 51))
        self.label_5.setStyleSheet("color: rgb(185, 110, 127);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.tabProduct)
        self.label_6.setGeometry(QtCore.QRect(260, 140, 71, 51))
        self.label_6.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_6.setStyleSheet("color: rgb(185, 110, 127);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.tabProduct)
        self.label_7.setGeometry(QtCore.QRect(240, 250, 91, 51))
        self.label_7.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_7.setStyleSheet("color: rgb(185, 110, 127);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.tabProduct)
        self.label_8.setGeometry(QtCore.QRect(150, 370, 181, 51))
        self.label_8.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_8.setStyleSheet("color: rgb(185, 110, 127);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.lineEditOnpromotion = QtWidgets.QLineEdit(parent=self.tabProduct)
        self.lineEditOnpromotion.setGeometry(QtCore.QRect(390, 360, 621, 61))
        self.lineEditOnpromotion.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.lineEditOnpromotion.setStyleSheet("background-color: rgb(250, 244, 236);\n"
"color: rgb(104, 83, 92);          \n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"border-radius: 20px;")
        self.lineEditOnpromotion.setObjectName("lineEditOnpromotion")
        self.btnPredictP = QtWidgets.QPushButton(parent=self.tabProduct)
        self.btnPredictP.setGeometry(QtCore.QRect(180, 500, 181, 51))
        self.btnPredictP.setStyleSheet(" background-color: #b96e7f;   \n"
"    color:#e8ddde ;                 \n"
"    border-radius: 10px;\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("../images/ic_buttonpredict.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnPredictP.setIcon(icon17)
        self.btnPredictP.setIconSize(QtCore.QSize(30, 30))
        self.btnPredictP.setObjectName("btnPredictP")
        self.label_9 = QtWidgets.QLabel(parent=self.tabProduct)
        self.label_9.setGeometry(QtCore.QRect(500, 500, 151, 51))
        self.label_9.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_9.setStyleSheet("color: rgb(185, 110, 127);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.lineEditSales = QtWidgets.QLineEdit(parent=self.tabProduct)
        self.lineEditSales.setGeometry(QtCore.QRect(670, 490, 381, 61))
        self.lineEditSales.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.lineEditSales.setStyleSheet("background-color: rgb(250, 244, 236);\n"
"color: rgb(104, 83, 92);          \n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"border-radius: 20px;")
        self.lineEditSales.setText("")
        self.lineEditSales.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditSales.setObjectName("lineEditSales")
        self.label_12 = QtWidgets.QLabel(parent=self.tabProduct)
        self.label_12.setGeometry(QtCore.QRect(220, 30, 41, 41))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("../images/ic_date.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.tabProduct)
        self.label_13.setGeometry(QtCore.QRect(210, 140, 41, 41))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("../images/ic_store.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.tabProduct)
        self.label_14.setGeometry(QtCore.QRect(200, 250, 41, 41))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("../images/ic_product.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.tabProduct)
        self.label_15.setGeometry(QtCore.QRect(110, 370, 41, 41))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("../images/ic_onpromotion.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.tabProduct)
        self.label_16.setGeometry(QtCore.QRect(530, 500, 41, 41))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("../images/ic_sale.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.dateEditDateP = QtWidgets.QDateEdit(parent=self.tabProduct)
        self.dateEditDateP.setGeometry(QtCore.QRect(390, 30, 621, 61))
        self.dateEditDateP.setStyleSheet("background-color: rgb(250, 244, 236);\n"
"color: rgb(104, 83, 92);          \n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"border-radius: 20px;")
        self.dateEditDateP.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.dateEditDateP.setDateTime(QtCore.QDateTime(QtCore.QDate(2013, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditDateP.setCalendarPopup(True)
        self.dateEditDateP.setCurrentSectionIndex(2)
        self.dateEditDateP.setObjectName("dateEditDateP")
        self.comboBoxStoreP = QtWidgets.QComboBox(parent=self.tabProduct)
        self.comboBoxStoreP.setGeometry(QtCore.QRect(390, 130, 621, 61))
        self.comboBoxStoreP.setStyleSheet("background-color: rgb(250, 244, 236);\n"
"color: rgb(104, 83, 92);          \n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"border-radius: 20px;")
        self.comboBoxStoreP.setObjectName("comboBoxStoreP")
        self.comboBoxFamily = QtWidgets.QComboBox(parent=self.tabProduct)
        self.comboBoxFamily.setGeometry(QtCore.QRect(390, 240, 621, 61))
        self.comboBoxFamily.setStyleSheet("background-color: rgb(250, 244, 236); \n"
"color: rgb(104, 83, 92);          \n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"border-radius: 20px;")
        self.comboBoxFamily.setObjectName("comboBoxFamily")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("../images/ic_product.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.tabProduct, icon18, "")
        self.tabDate = QtWidgets.QWidget()
        self.tabDate.setObjectName("tabDate")
        self.label_10 = QtWidgets.QLabel(parent=self.tabDate)
        self.label_10.setGeometry(QtCore.QRect(300, 30, 61, 51))
        self.label_10.setStyleSheet("color: rgb(185, 110, 127);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.dateEditDateD = QtWidgets.QDateEdit(parent=self.tabDate)
        self.dateEditDateD.setGeometry(QtCore.QRect(420, 30, 611, 61))
        self.dateEditDateD.setStyleSheet("background-color: rgb(250, 244, 236);  \n"
"color: rgb(104, 83, 92);        \n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"border-radius: 20px;")
        self.dateEditDateD.setDateTime(QtCore.QDateTime(QtCore.QDate(2013, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditDateD.setCalendarPopup(True)
        self.dateEditDateD.setObjectName("dateEditDateD")
        self.label_11 = QtWidgets.QLabel(parent=self.tabDate)
        self.label_11.setGeometry(QtCore.QRect(300, 160, 71, 51))
        self.label_11.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_11.setStyleSheet("color: rgb(185, 110, 127);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.comboBoxStoreD = QtWidgets.QComboBox(parent=self.tabDate)
        self.comboBoxStoreD.setGeometry(QtCore.QRect(420, 160, 611, 61))
        self.comboBoxStoreD.setStyleSheet("background-color: rgb(250, 244, 236); \n"
"color: rgb(104, 83, 92);          \n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"border-radius: 20px;")
        self.comboBoxStoreD.setObjectName("comboBoxStoreD")
        self.btnPredictD = QtWidgets.QPushButton(parent=self.tabDate)
        self.btnPredictD.setGeometry(QtCore.QRect(150, 280, 181, 51))
        self.btnPredictD.setStyleSheet(" background-color: #b96e7f;   \n"
"    color:#e8ddde ;                 \n"
"    border-radius: 10px;\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.btnPredictD.setIcon(icon17)
        self.btnPredictD.setIconSize(QtCore.QSize(30, 30))
        self.btnPredictD.setObjectName("btnPredictD")
        self.tableWidgetDate = QtWidgets.QTableWidget(parent=self.tabDate)
        self.tableWidgetDate.setGeometry(QtCore.QRect(410, 270, 621, 301))
        self.tableWidgetDate.setStyleSheet("color: rgb(185, 110, 127);\n"
"background-color: rgb(250, 244, 236);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"\n"
"")
        self.tableWidgetDate.setObjectName("tableWidgetDate")
        self.tableWidgetDate.setColumnCount(2)
        self.tableWidgetDate.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDate.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDate.setHorizontalHeaderItem(1, item)
        self.label_17 = QtWidgets.QLabel(parent=self.tabDate)
        self.label_17.setGeometry(QtCore.QRect(250, 30, 41, 41))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("../images/ic_date.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.tabDate)
        self.label_18.setGeometry(QtCore.QRect(250, 160, 41, 41))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("../images/ic_store.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("../images/ic_day.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.tabDate, icon19, "")
        self.label_4 = QtWidgets.QLabel(parent=self.tabWidgetPagePredict)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 1171, 691))
        self.label_4.setStyleSheet("background-color: rgb(232, 221, 222);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.tabWidget.raise_()
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("../images/ic_predict.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.MainWindow.addTab(self.tabWidgetPagePredict, icon20, "")
        Admin.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Admin)
        self.statusbar.setObjectName("statusbar")
        Admin.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=Admin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1189, 26))
        self.menubar.setObjectName("menubar")
        self.menuBack = QtWidgets.QMenu(parent=self.menubar)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menuBack.setFont(font)
        self.menuBack.setObjectName("menuBack")
        Admin.setMenuBar(self.menubar)
        self.actionConnect = QtGui.QAction(parent=Admin)
        self.actionConnect.setObjectName("actionConnect")
        self.actionBack = QtGui.QAction(parent=Admin)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("../images/ic_back.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionBack.setIcon(icon21)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionBack.setFont(font)
        self.actionBack.setObjectName("actionBack")
        self.menuBack.addAction(self.actionBack)
        self.menubar.addAction(self.menuBack.menuAction())

        self.retranslateUi(Admin)
        self.MainWindow.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Admin)

    def retranslateUi(self, Admin):
        _translate = QtCore.QCoreApplication.translate
        Admin.setWindowTitle(_translate("Admin", "MainWindow"))
        self.MainWindow.setToolTip(_translate("Admin", "<html><head/><body><p>hi</p></body></html>"))
        self.label_3.setText(_translate("Admin", "Tables"))
        self.comboBoxData.setItemText(0, _translate("Admin", "Holidays_Events"))
        self.comboBoxData.setItemText(1, _translate("Admin", "Items"))
        self.comboBoxData.setItemText(2, _translate("Admin", "Stores"))
        self.comboBoxData.setItemText(3, _translate("Admin", "Oil"))
        self.comboBoxData.setItemText(4, _translate("Admin", "Train"))
        self.comboBoxData.setItemText(5, _translate("Admin", "Test"))
        self.comboBoxData.setItemText(6, _translate("Admin", "Transaction"))
        self.comboBoxData.setItemText(7, _translate("Admin", "Users"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Admin", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Admin", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Admin", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Admin", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Admin", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Admin", "New Column"))
        self.MainWindow.setTabText(self.MainWindow.indexOf(self.tabWidgetPageData), _translate("Admin", "Database"))
        self.groupBoxChart_2.setTitle(_translate("Admin", "Chart Visualization:"))
        self.groupBox.setTitle(_translate("Admin", "Function:"))
        self.btnPeakLowSales.setText(_translate("Admin", "Peak–Low Sales"))
        self.btnSalesByWeekday.setText(_translate("Admin", "Sales by Weekday"))
        self.btnEarthquakeSales.setText(_translate("Admin", "Earthquake Sales Trend"))
        self.btnHolidayVsNormal.setText(_translate("Admin", "Holiday and Normal Sales"))
        self.btnCorrelationHeatmap.setText(_translate("Admin", "Correlation Heatmap"))
        self.btnLagPlot.setText(_translate("Admin", "Transactions Lag Plot"))
        self.btnYearlySales.setText(_translate("Admin", "Yearly Sales"))
        self.groupBox_2.setTitle(_translate("Admin", "List of data"))
        item = self.tableWidgetListofData.horizontalHeaderItem(0)
        item.setText(_translate("Admin", "New Column"))
        item = self.tableWidgetListofData.horizontalHeaderItem(1)
        item.setText(_translate("Admin", "New Column"))
        self.MainWindow.setTabText(self.MainWindow.indexOf(self.tabWidgetPageStatistic), _translate("Admin", "Statistic"))
        self.label_5.setText(_translate("Admin", "Date"))
        self.label_6.setText(_translate("Admin", "Store"))
        self.label_7.setText(_translate("Admin", "Family"))
        self.label_8.setText(_translate("Admin", "Onpromotion"))
        self.btnPredictP.setText(_translate("Admin", "Predict"))
        self.label_9.setText(_translate("Admin", "Sales"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProduct), _translate("Admin", "Predict one product group"))
        self.label_10.setText(_translate("Admin", "Date"))
        self.label_11.setText(_translate("Admin", "Store"))
        self.btnPredictD.setText(_translate("Admin", "Predict"))
        item = self.tableWidgetDate.horizontalHeaderItem(0)
        item.setText(_translate("Admin", "Family"))
        item = self.tableWidgetDate.horizontalHeaderItem(1)
        item.setText(_translate("Admin", "Sales"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDate), _translate("Admin", "Predict by day"))
        self.MainWindow.setTabText(self.MainWindow.indexOf(self.tabWidgetPagePredict), _translate("Admin", "Predict"))
        self.menuBack.setTitle(_translate("Admin", "Menu"))
        self.actionConnect.setText(_translate("Admin", "Connect"))
        self.actionBack.setText(_translate("Admin", "Back"))
