# Form implementation generated from reading ui file 'D:\python\Hocmay\Final_HocMay\UI\UserHomepage.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UserHomepage(object):
    def setupUi(self, UserHomepage):
        UserHomepage.setObjectName("UserHomepage")
        UserHomepage.resize(1189, 788)
        UserHomepage.setMaximumSize(QtCore.QSize(1189, 16777215))
        self.centralwidget = QtWidgets.QWidget(parent=UserHomepage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1191, 751))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../images/Background.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -10, 1191, 761))
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
" \n"
"    padding: 10px;\n"
" border: 1px solid #faf4ec; \n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 151, 91))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../images/logo.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.labelProfile = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelProfile.setGeometry(QtCore.QRect(1050, 30, 41, 41))
        self.labelProfile.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.labelProfile.setStyleSheet("")
        self.labelProfile.setText("")
        self.labelProfile.setPixmap(QtGui.QPixmap("../images/ic_profile.png"))
        self.labelProfile.setScaledContents(True)
        self.labelProfile.setObjectName("labelProfile")
        self.labelLogout = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelLogout.setGeometry(QtCore.QRect(1120, 30, 51, 41))
        self.labelLogout.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.labelLogout.setText("")
        self.labelLogout.setPixmap(QtGui.QPixmap("../images/ic_logout.png"))
        self.labelLogout.setScaledContents(True)
        self.labelLogout.setObjectName("labelLogout")
        self.labelAdmin = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelAdmin.setGeometry(QtCore.QRect(0, 0, 1191, 101))
        self.labelAdmin.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.labelAdmin.setStyleSheet("background-color: rgb(221, 160, 175);\n"
"\n"
"\n"
"")
        self.labelAdmin.setText("")
        self.labelAdmin.setObjectName("labelAdmin")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 100, 1191, 651))
        self.tabWidget.setStyleSheet("/* Tab đang được chọn (active) */\n"
"QTabBar::tab:selected {\n"
"    min-width: 300px;     /* Độ rộng tối thiểu của mỗi tab */\n"
"    min-height: 35px;\n"
"    background-color: #b96e7f;     /* màu hồng đậm khi chọn */\n"
"    color:#e8ddde ;                 /* chữ trắng khi chọn */\n"
"    font-weight: bold;\n"
"    border-radius: 10px;\n"
"    font: 16pt \"MS Shell Dlg 2\";\n"
"   font-weight: bold;\n"
"}\n"
"\n"
"/* Tab chưa được chọn */\n"
"QTabBar::tab:!selected {\n"
"    min-width: 300px;     /* Độ rộng tối thiểu của mỗi tab */\n"
"    min-height: 35px;\n"
"    background-color: #e8ddde;    /* hồng nhạt khi chưa chọn */\n"
"    color: #b96e7f;               /* chữ nâu đỏ */\n"
"    font-weight: normal;\n"
"    border-radius: 10px;\n"
"    font: 16pt \"MS Shell Dlg 2\";\n"
"   font-weight: bold;\n"
"}\n"
"\n"
"/* Khi rê chuột vào tab (hover) */\n"
"QTabBar::tab:hover {\n"
"    background-color: #dda0af;    /* hồng sáng hơn khi hover */\n"
"}\n"
"\n"
"/* Viền xung quanh vùng nội dung tab */\n"
"QTabWidget::pane {\n"
"    border: 2px solid #dda0af;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"")
        self.tabWidget.setIconSize(QtCore.QSize(50, 40))
        self.tabWidget.setObjectName("tabWidget")
        self.tabHomepage = QtWidgets.QWidget()
        self.tabHomepage.setObjectName("tabHomepage")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.tabHomepage)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 1171, 581))
        self.scrollArea.setStyleSheet("background-color: #e8ddde;   \n"
"color: rgb(104, 83, 92);        \n"
"font: 13pt \"MS Shell Dlg 2\";\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1169, 579))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/ic_home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.tabHomepage, icon, "")
        self.tabRecomendations = QtWidgets.QWidget()
        self.tabRecomendations.setObjectName("tabRecomendations")
        self.label_10 = QtWidgets.QLabel(parent=self.tabRecomendations)
        self.label_10.setGeometry(QtCore.QRect(70, 10, 121, 51))
        self.label_10.setStyleSheet("color: rgb(104, 83, 92);        \n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_17 = QtWidgets.QLabel(parent=self.tabRecomendations)
        self.label_17.setGeometry(QtCore.QRect(80, 20, 41, 41))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("../images/ic_date.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_11 = QtWidgets.QLabel(parent=self.tabRecomendations)
        self.label_11.setGeometry(QtCore.QRect(40, 70, 151, 51))
        self.label_11.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_11.setStyleSheet("color: rgb(104, 83, 92);        \n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_18 = QtWidgets.QLabel(parent=self.tabRecomendations)
        self.label_18.setGeometry(QtCore.QRect(70, 70, 41, 41))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("../images/ic_store.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.dateEditDate = QtWidgets.QDateEdit(parent=self.tabRecomendations)
        self.dateEditDate.setGeometry(QtCore.QRect(230, 10, 611, 41))
        self.dateEditDate.setStyleSheet("background-color: rgb(206, 190, 193);\n"
"color: rgb(104, 83, 92);        \n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"border-radius: 15px;")
        self.dateEditDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2013, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditDate.setCalendarPopup(True)
        self.dateEditDate.setCurrentSectionIndex(2)
        self.dateEditDate.setObjectName("dateEditDate")
        self.comboBoxStore = QtWidgets.QComboBox(parent=self.tabRecomendations)
        self.comboBoxStore.setGeometry(QtCore.QRect(230, 80, 611, 41))
        self.comboBoxStore.setStyleSheet("background-color: rgb(206, 190, 193);\n"
"color: rgb(104, 83, 92);          \n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"border-radius: 15px;")
        self.comboBoxStore.setObjectName("comboBoxStore")
        self.btnPredictRecomendation = QtWidgets.QPushButton(parent=self.tabRecomendations)
        self.btnPredictRecomendation.setGeometry(QtCore.QRect(890, 40, 261, 51))
        self.btnPredictRecomendation.setStyleSheet(" background-color: #b96e7f;   \n"
"    color:#e8ddde ;                 \n"
"    border-radius: 10px;\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/ic_recomend.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnPredictRecomendation.setIcon(icon1)
        self.btnPredictRecomendation.setIconSize(QtCore.QSize(30, 30))
        self.btnPredictRecomendation.setObjectName("btnPredictRecomendation")
        self.listView = QtWidgets.QListView(parent=self.tabRecomendations)
        self.listView.setGeometry(QtCore.QRect(180, 200, 811, 381))
        self.listView.setStyleSheet("color: rgb(185, 110, 127);\n"
"background-color: rgb(250, 244, 236);\n"
"border: 1px solid #faf4ec; \n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"")
        self.listView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectColumns)
        self.listView.setTextElideMode(QtCore.Qt.TextElideMode.ElideMiddle)
        self.listView.setObjectName("listView")
        self.label_3 = QtWidgets.QLabel(parent=self.tabRecomendations)
        self.label_3.setGeometry(QtCore.QRect(180, 140, 811, 41))
        self.label_3.setStyleSheet("background-color: rgb(221, 160, 175);\n"
" color: rgb(104, 83, 92);        \n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/ic_recomendation.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.tabRecomendations, icon2, "")
        self.labelHello = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelHello.setGeometry(QtCore.QRect(690, 30, 331, 41))
        self.labelHello.setStyleSheet("color: rgb(104, 83, 92); \n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.labelHello.setText("")
        self.labelHello.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelHello.setObjectName("labelHello")
        self.labelHello_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelHello_2.setGeometry(QtCore.QRect(180, 10, 121, 71))
        self.labelHello_2.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.labelHello_2.setStyleSheet(" color: rgb(104, 83, 92);        \n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.labelHello_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelHello_2.setObjectName("labelHello_2")
        self.label.raise_()
        self.label_2.raise_()
        self.labelAdmin.raise_()
        self.labelProfile.raise_()
        self.labelLogout.raise_()
        self.label_5.raise_()
        self.tabWidget.raise_()
        self.labelHello.raise_()
        self.labelHello_2.raise_()
        UserHomepage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=UserHomepage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1189, 26))
        self.menubar.setObjectName("menubar")
        UserHomepage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=UserHomepage)
        self.statusbar.setObjectName("statusbar")
        UserHomepage.setStatusBar(self.statusbar)

        self.retranslateUi(UserHomepage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UserHomepage)

    def retranslateUi(self, UserHomepage):
        _translate = QtCore.QCoreApplication.translate
        UserHomepage.setWindowTitle(_translate("UserHomepage", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHomepage), _translate("UserHomepage", "Homepage"))
        self.label_10.setText(_translate("UserHomepage", "Date"))
        self.label_11.setText(_translate("UserHomepage", "Store"))
        self.btnPredictRecomendation.setText(_translate("UserHomepage", "Recommendation"))
        self.label_3.setText(_translate("UserHomepage", "Top 5 Best-Selling Products"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRecomendations), _translate("UserHomepage", "Recommendations"))
        self.labelHello_2.setText(_translate("UserHomepage", "Admin"))
